### ISSUE TITLE
Javascript Not Working On ios

### ISSUE THREAD

**Issue by xOnlyFadi** [rs1703/koushoku#2]
Hi koushoku Developer when i was using the site on my iphone the javascript is broken on the reader here is a video

https://user-images.githubusercontent.com/63213308/158079876-3ff62fe9-ab89-4c96-ae9d-a9d99a7c306a.mp4

**Comment by rs1703** [comment]
Seems like it doesn't even load the css, js and images. Have you tried clearing the site cache?

**Comment by xOnlyFadi** [comment]
> Seems like it doesn't even load the css, js and images. Have you tried clearing the site cache?

i did many times it and still gives the same thing

**Comment by rs1703** [comment]
The serviceWorker probably doesn't work on ios. I have removed it, can you try it again? Try clearing the cache beforehand just to be safe. If it still doesn't work then it probably has something to do with Cloudflare because we had a massive cache purge yesterday, so maybe using vpn would fix it.

**Comment by xOnlyFadi** [comment]
> The serviceWorker probably doesn't work on ios. I have removed it, can you try it again? Try clearing the cache beforehand just to be safe. If it still doesn't work then it probably has something to do with Cloudflare because we had a massive cache purge yesterday, so maybe using vpn would fix it.

the site started working fine with no problems css, js and images are working

**Comment by rs1703** [comment]
Glad to hear that.
