### ISSUE TITLE
foreign key duplicate after each time the backend restart

### ISSUE THREAD

**Issue by thang1160** [rs1703/koushoku#9]
![image](https://user-images.githubusercontent.com/35557579/166500476-47e2c328-59ab-416f-be47-c7c3b263415d.png)

It occurs because of the `ALTER TABLE ADD COLUMN IF NOT EXISTS ... REFERENCES ...` commands.
I think we should check if the constraint exists or not beforehand, OR we could delete it and add it again (the easy & expensive way)
```
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'archive_submission_id_fkey') THEN
        ALTER TABLE archive
            ADD CONSTRAINT archive_submission_id_fkey
            FOREIGN KEY (submission_id) REFERENCES submission(id) ON DELETE CASCADE;
    END IF;
END;
$$;
```

**Comment by rs1703** [comment]
Thank you for noticing this, the latest commit should fix this out.
